server:
  http_listen_port: 3200
  grpc_listen_port: 4317
  http_api_prefix: /
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m
compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 10_000_000
    block_retention: 24h
storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
