apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentic.fullname" . }}-worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: {{ include "agentic.name" . }}
      component: worker
  template:
    metadata:
      labels:
        app: {{ include "agentic.name" . }}
        component: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          envFrom:
            - secretRef:
                name: agentic-env
          resources: {{- toYaml .Values.resources.worker | nindent 10 }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
