apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentic.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: {{ include "agentic.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "agentic.name" . }}
        component: api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          resources: {{- toYaml .Values.resources.api | nindent 10 }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: agentic-env
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
