name: Helm Chart Publish

on:
  push:
    tags: ["v*.*.*"]

jobs:
  helm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      CHART_DIR: charts/agentic
      REGISTRY: ghcr.io
      ORG: ${{ github.repository_owner }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Update chart version
        run: |
          yq -i '.version = env(VERSION) | .appVersion = env(VERSION)' $CHART_DIR/Chart.yaml || true
      - name: Package chart
        run: |
          helm package $CHART_DIR --destination .
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Push chart to GHCR (OCI)
        run: |
          CHART_TGZ=$(ls agentic-*.tgz | head -n1)
          helm push "$CHART_TGZ" oci://ghcr.io/${{ env.ORG }}/charts
      - name: Create GitHub Release and attach chart
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            agentic-*.tgz
