name: SDKs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'app/api/**'
      - 'app/models/**'

jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci || npm i
      - name: Launch API (background)
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8080 &
          sleep 5
      - name: Generate SDKs
        run: |
          bash scripts/generate_sdks.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdks
          path: |
            sdks/typescript
            sdks/python
