image:
  api:
    repository: ghcr.io/REPLACE_ME/agentic-api
    tag: latest
    pullPolicy: IfNotPresent
  worker:
    repository: ghcr.io/REPLACE_ME/agentic-worker
    tag: latest
    pullPolicy: IfNotPresent

replicaCount:
  api: 1
  worker: 1

env:
  ENV: "prod"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_URL_QUEUE: "redis://redis:6379/2"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/agentic"
  S3_BUCKET: "agentic-prod"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.default.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "agentic-backend"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  api:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  worker:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "2Gi"

hpa:
  api:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  worker:
    enabled: false  # we scale worker via KEDA instead
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

keda:
  enabled: true
  redisAddress: "redis://redis.default.svc.cluster.local:6379"
  queueName: "celery"  # Celery default queue name
  minReplicas: 0
  maxReplicas: 50
  pollingInterval: 5          # seconds
  cooldownPeriod: 60          # seconds
  listLength: 5               # scale when > N pending

serviceAccount:
  create: true
  name: agentic
  annotations: {}   # e.g., eks.amazonaws.com/role-arn: arn:aws:iam::<acct>:role/<role>

externalSecrets:
  enabled: true
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-store
  dataFrom:
    - extract:
        key: agentic/app  # replace with AWS Secrets Manager name

ingress:
  enabled: false
  className: alb
  hosts:
    - host: agentic.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

keda:
  mode: list  # or "streams"
  streams:
    stream: "celery-stream"
    consumerGroup: "agentic-workers"
    pendingEntriesCount: "5"
    enableTLS: "true"
