version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-agentic}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-agentic}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL_SYNC}
      ENV: ${ENV}
      PYTHONPATH: /srv
    command: sh -lc "python -m alembic -c db/alembic.ini upgrade head"

  api:
    build: .
    depends_on:
      - migrate
      - redis
    environment:
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      ARTIFACTS_DIR: ${ARTIFACTS_DIR}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_URL_QUEUE: ${REDIS_URL_QUEUE}
      ENV: ${ENV}
      APP_NAME: ${APP_NAME}
      WEBHOOK_HMAC_SECRET: ${WEBHOOK_HMAC_SECRET}
      RATE_LIMIT_USER_PER_MIN: ${RATE_LIMIT_USER_PER_MIN}
      RATE_LIMIT_TENANT_PER_MIN: ${RATE_LIMIT_TENANT_PER_MIN}
      PYTHONPATH: /srv
      PLUGINS_DIR: /srv/plugins
      MODELS_CONFIG: /srv/config/models.yaml
      SERVICE_FLAGS: "public:*"   # ← enable all services for the "public" tenant
    volumes:
      # repo-root mounts (compose file is in ./src)
      - "../artifacts:${ARTIFACTS_DIR}"
      - "../plugins:/srv/plugins"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    ports: ["8081:8080"]   # convenient direct access for dev
    expose: ["8080"]       # for internal reverse proxy (caddy)
    restart: unless-stopped

  worker:
    build: .
    depends_on:
      - migrate
      - redis
    environment:
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      ARTIFACTS_DIR: ${ARTIFACTS_DIR}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_URL_QUEUE: ${REDIS_URL_QUEUE}
      ENV: ${ENV}
      APP_NAME: ${APP_NAME}
      WEBHOOK_HMAC_SECRET: ${WEBHOOK_HMAC_SECRET}
      PYTHONPATH: /srv
      PLUGINS_DIR: /srv/plugins
      MODELS_CONFIG: /srv/config/models.yaml
      SERVICE_FLAGS: "public:*"   # ← worker sees same tenant service enablement
    volumes:
      - "../artifacts:${ARTIFACTS_DIR}"
      - "../plugins:/srv/plugins"
    command: celery -A app.workers.celery_app worker -Q cpu -P solo -c 1 --loglevel=INFO
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pg_data:
  caddy_data:
  caddy_config:
